# Generated by Django 3.1.7 on 2021-03-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_remove_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='semester',
            new_name='Batch',
        ),
    ]
